const menu = [
  {
    id: 1,
    title: 'Raisin Delight Frappe',
    category: 'Seasonal menu',
    price: 50000,
    img: "https://soal.staging.id/img/Raisin Delight Frappe.png",
    desc: "a timeless classic. A sweet, creamy, rich, flavorful experience of vanilla cream and juicy ripe raisins with a hint of warmth",
  },
  {
    id: 2,
    title: 'Green Tea Latte',
    category: 'Seasonal menu',
    price: 47000,
    img:  "https://soal.staging.id/img/Green Tea Latte.png",
    desc: "A perfect combination between Maxx Coffee’s special green tea and fresh milk.",
  },
  {
    id: 3,
    title: 'Melaka Brulee Latte',
    category: 'Seasonal menu',
    price: 40000,
    img: "https://soal.staging.id/img/Melaka Brulee Latte.png",
    desc: "A Caffe Latte packed with a rich and intense Melaka brown sugar flavor with a creamier custardy flavor and body.",
  },
  {
    id: 4,
    title: 'country delight',
    category: 'Coffe',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'Cold Brew',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'Best Seller',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'Best Seller',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'Best Seller',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'Best Seller',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
